### ISSUE TITLE
Fails on Saxon 9.9.1.1

### ISSUE THREAD

**Issue by AirQuick** [dmj/schxslt-ant#2]
I got this exception when I ran a task with Saxon-HE 9.9.1.1. The same set of files worked fine with 9.8.
I don't know if the problem is in Saxon or schxslt-ant. Anyway, is it working on your end?
```
build:
[schematron] Generating validation stylesheet for Schematron '/home/test/test/demo-01.sch'

BUILD FAILED
/home/test/test/build.xml:6: java.lang.UnsupportedOperationException
	at net.sf.saxon.event.Receiver.append(Receiver.java:232)
	at net.sf.saxon.event.ProxyReceiver.append(ProxyReceiver.java:234)
	at net.sf.saxon.event.ComplexContentOutputter.append(ComplexContentOutputter.java:611)
	at net.sf.saxon.expr.VariableReference.lambda$process$0(VariableReference.java:589)
	at net.sf.saxon.tree.iter.SingletonIterator.forEachOrFail(SingletonIterator.java:152)
	at net.sf.saxon.expr.VariableReference.process(VariableReference.java:589)
	at net.sf.saxon.expr.instruct.Choose.processLeavingTail(Choose.java:898)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:721)
	at net.sf.saxon.expr.instruct.Block.processLeavingTail(Block.java:735)
	at net.sf.saxon.expr.instruct.NamedTemplate.expand(NamedTemplate.java:243)
	at net.sf.saxon.expr.instruct.CallTemplate$CallTemplatePackage.processLeavingTail(CallTemplate.java:518)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:438)
	at net.sf.saxon.trans.rules.TextOnlyCopyRuleSet.process(TextOnlyCopyRuleSet.java:71)
	at net.sf.saxon.trans.Mode.applyTemplates(Mode.java:482)
	at net.sf.saxon.trans.XsltController.applyTemplates(XsltController.java:733)
	at net.sf.saxon.s9api.AbstractXsltTransformer.applyTemplatesToSource(AbstractXsltTransformer.java:347)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:338)
	at net.sf.saxon.jaxp.TransformerImpl.transform(TransformerImpl.java:71)
	at name.dmaus.schxslt.Compiler.compile(Compiler.java:63)
	at name.dmaus.schxslt.ant.Schematron.<init>(Schematron.java:60)
	at name.dmaus.schxslt.ant.Task.execute(Task.java:83)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:448)
	at org.apache.tools.ant.Target.performTasks(Target.java:469)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1370)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1260)
	at org.apache.tools.ant.Main.runBuild(Main.java:849)
	at org.apache.tools.ant.Main.startAnt(Main.java:228)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:283)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```

**Comment by dmj** [comment]
I can confirm this on my side.

**Comment by dmj** [comment]
This seems to be a problem in Saxon. The offending line is https://github.com/dmj/schxslt/blob/master/src/main/resources/xslt/include.xsl#L27 -- if I replace the xsl:sequence with a xsl:copy-of then there are no more crashes.

**Comment by dmj** [comment]
https://saxonica.plan.io/issues/4121 fixed upstream

**Comment by AirQuick** [comment]
Thanks for the investigation. I'll wait for the next maintenance release.

**Comment by AirQuick** [comment]
Not reproduced on Saxon 9.9.1.2.

**Comment by dmj** [comment]
Thanks for checking
